<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$company = $job->getPackage()->getCompany();

$this->headTitle($job->getName());
$this->headTitle($category->getPluralName());

?>
<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('company/companyItem', ['slugCompanyName' => $company->getSlugName()]) ?>">
                    <?= $company->getName(); ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('company/companyItem/joblist', ['slugCompanyName' => $company->getSlugName(), 'category' => $job->getCategory()->getSlug() ]) ?>">
                    <?= $category->getPluralName() ?>
                </a>
            </li>
            <li class="active">
                <?= $job->getName() ?>
            </li>
        </ol>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $job->getName() ?></h1>
                <ul class="details-list">
                    <li>
                        <a href="<?= $this->url('company/companyItem', ['slugCompanyName' => $company->getSlugName()]) ?>">
                            <?= $company->getName() ?>
                        </a>
                    </li>
                    <?php if (!is_null($job->getLocation())): ?>
                        <li><?= $job->getLocation() ?></li>
                    <?php endif; ?>
                    <li>
                        <?php if($job->getTimestamp()->isToday()): ?>
                            <?= $this->translate('Posted today') ?>
                        <?php else: ?>
                            <?= sprintf($this->translate('Posted %s'), $job->getTimestamp()->diffForHumans()) ?>
                        <?php endif ?>
                        (<?= $job->getTimestamp()->format('d-m-Y') ?>)
                    </li>
                    <li>
                        <span class="label label-default job-label" data-label="CSE" data-toggle="tooltip" title="Computer Science & Engineering">CSE</span>
                        <span class="label label-default job-label" data-label="DS" data-toggle="tooltip" title="Data Science">DS</span>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="job-description text-justify markdown"><?= $this->markdown($job->getDescription()) ?></div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-image">
                        <img
                            src="<?= $this->fileUrl($company->getTranslationFromLocale($locale)->getLogo()); ?>"
                            alt="<?= $escaper->escapeHtmlAttr($company->getName()); ?>" />
                    </div>
                    <div class="panel-heading">
                        <span class="h4"><?= $this->translate('Contact') ?></span>
                    </div>
                    <div class="panel-body">
                        <dl class="icon-list">
                            <?php if (!empty($job->getContactName())): ?>
                                <dt><span class="glyphicon glyphicon-user" title="<?= $this->translate('Contact person') ?>"></span></dt>
                                <dd><?= $job->getContactName() ?></dd>
                            <?php endif; ?>
                            <?php if (!empty($job->getPhone())): ?>
                                <dt><span class="glyphicon glyphicon-earphone" title="<?= $this->translate('Telephone number') ?>"></span></dt>
                                <dd><a href="tel:<?= rawurlencode($job->getPhone()) ?>"><?= $job->getPhone() ?></a></dd>
                            <?php endif; ?>
                            <?php if (!empty($job->getEmail())): ?>
                                <dt><span class="glyphicon glyphicon-envelope" title="<?= $this->translate('Email address') ?>"></span></dt>
                                <dd><a href="mailto:<?= rawurlencode($job->getEmail()) ?>"><?= $job->getEmail() ?></a></dd>
                            <?php endif; ?>
                        </dl>
                    </div>
                </div>
                <?php if (!is_null($job->getAttachment())): ?>
                    <a href="<?= $this->fileUrl($job->getAttachment()) ?>" class="panel-footer__link--primary" target="_blank">
                        <?= $this->translate('Download attachment') ?>
                    </a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>
<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>
