<?php

$locale = $this->translator->getLocale();
$escaper = new Zend\Escaper\Escaper('utf-8');

$company = $job->getPackage()->getCompany();

$this->headTitle($job->getName());
$this->headTitle($category->getPluralName());

?>
<section class="section section-breadcrumb">
    <div class="container">
        <ol class="breadcrumb">
            <li>
                <a href="<?= $this->url('company') ?>">
                    <?= $this->translate('Companies') ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('company/companyItem', ['slugCompanyName' => $company->getSlugName()]) ?>">
                    <?= $company->getName(); ?>
                </a>
            </li>
            <li>
                <a href="<?= $this->url('company/companyItem/joblist', ['slugCompanyName' => $company->getSlugName(), 'category' => $job->getCategory()->getSlug() ]) ?>">
                    <?= $category->getPluralName() ?>
                </a>
            </li>
            <li class="active">
                <?= $job->getName() ?>
            </li>
        </ol>
    </div>
</section>
<section class="section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1><?= $job->getName() ?></h1>
                <ul class="details-list">
                    <?php if (!$job->isActive()): ?>
                    <li>
                         <span
                             class="label label-warning" data-toggle="tooltip"
                             title="<?= sprintf($this->translate("This %s isn't publicly visible"), strtolower($category->getName())) ?>">
                             <?= $this->translate('Hidden') ?>
                         </span>
                    </li>
                    <?php endif; ?>
                    <li>
                        <a href="<?= $this->url('company/companyItem', ['slugCompanyName' => $company->getSlugName()]) ?>">
                            <?= $company->getName() ?>
                        </a>
                    </li>
                    <?php if (!is_null($job->getLocation())): ?>
                        <li><?= $job->getLocation() ?></li>
                    <?php endif; ?>
                    <li>
                        <?php if($job->getTimestamp()->isToday()): ?>
                            <?= $this->translate('Posted today') ?>
                        <?php else: ?>
                            <?= sprintf($this->translate('Posted %s'), $job->getTimestamp()->diffForHumans()) ?>
                        <?php endif ?>
                        (<?= $job->getTimestamp()->format('d-m-Y') ?>)
                    </li>
                    <!--<li>
                        <span class="label label-default job-label" data-label="CSE" data-toggle="tooltip" title="Computer Science & Engineering">CSE</span>
                    </li>-->
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <?php if (empty($job->getDescription())): ?>
                    <p><em><?= $this->translate('No description available.') ?></em></p>
                <?php else: ?>
                    <div class="job-description text-justify markdown">
                        <?= $this->markdown($job->getDescription()) ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <?php if (!is_null($job->getAttachment())): ?>
                            <a href="<?= $this->fileUrl($job->getAttachment()) ?>" class="panel-footer__link--primary" target="_blank">
                                <?= $this->translate('Download attachment') ?>
                            </a>
                        <?php endif; ?>
                    </div>
                </div>
                <?= $this->partial('partial/company/company/contact.phtml', [
                    'locale'  => $locale,
                    'company' => $company,
                    'contact' => $job->getContactName(),
                    'phone'   => $job->getPhone(),
                    'email'   => $job->getEmail(),
                ]) ?>
            </div>
        </div>
    </div>
</section>
<script>
    $('[data-toggle="tooltip"]').tooltip();
</script>
