<div class="panel panel-default panel-company">
    <div class="panel-image">
        <img
            src="<?= $this->fileUrl($company->getTranslationFromLocale($locale)->getLogo()); ?>"
            alt="Logo" />
    </div>
    <div class="panel-heading">
        <span class="h4"><?= $this->translate('Contact') ?></span>
    </div>
    <div class="panel-body">
        <table class="table-contact-details">
            <tbody>
            <?php if (!empty($contact)): ?>
            <tr>
                <td>
                    <span class="glyphicon glyphicon-user" title="<?= $this->translate('Contact person') ?>"></span>
                </td>
                <td><?= $contact ?></td>
            </tr>
            <?php endif; ?>
            <?php if (!empty($phone)): ?>
            <tr>
                <td>
                    <span class="glyphicon glyphicon-earphone" title="<?= $this->translate('Telephone number') ?>"></span>
                </td>
                <td>
                    <a href="tel:<?= rawurlencode($phone) ?>"><?= $phone ?></a>
                </td>
            </tr>
            <?php endif; ?>
            <?php if (!empty($email)): ?>
            <tr>
                <td>
                    <span class="glyphicon glyphicon-envelope" title="<?= $this->translate('Email address') ?>"></span>
                </td>
                <td>
                    <a href="mailto:<?= rawurlencode($email) ?>"><?= $email ?></a>
                </td>
            </tr>
            <?php endif; ?>
            <?php if (!empty($website)): ?>
            <tr>
                <td>
                    <span class="glyphicon glyphicon-globe" title="<?= $this->translate('Website') ?>"></span>
                </td>
                <td>
                    <a href="<?= $website ?>" target="_blank"><?= $website ?></a>
                </td>
            </tr>
            <?php endif; ?>
            <?php if (!empty($address)): ?>
            <tr>
                <td>
                    <span class="glyphicon glyphicon-home" title="<?= $this->translate('Address') ?>"></span>
                </td>
                <td><?= nl2br($address) ?></td>
            </tr>
            <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>