<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<div class="row">
<?php foreach($form->getLanguages() as $lang):
$langDesc = $languages[$lang]
?>
<div class="col-md-6">
<h1><?= $this->translate($langDesc);?></h1>
<?php
$fieldset = $form->get('jobs')->get($lang);
?>
<?php
$element = $fieldset->get('id');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('name');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('slugName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('website');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('category');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('description');
$element->setAttribute('style', 'width:100%; height:10em; resize:none');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formTextArea($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('active');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('contactName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('phone');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('email');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('attachment_file');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php if (isset($job) && !is_null($job->getAttachment())): ?>
<div class="form-group">
    <label class="control-label col-sm-2">
        <?= $this->translate('Current attachment') ?>
    </label>
    <div class="col-sm-10">
        <a class="btn btn-default" href="<?= $this->fileUrl($job->getAttachment()); ?>" >
            <?= $this->translate('View attachment'); ?>
        </a>
    </div>
</div>

<?php endif;?>
</div>
<?php endforeach;?>
</div>

<div class="row">
    <div class="col-md-12">
        <hr />
        <h3><?= $this->translate('Labels') ?></h3>
        <p id="labels-feedback--empty" class="text-muted" style="display: none;">
            <?= $this->translate('No labels have been added yet') ?>
        </p>
        <?php ob_start(); ?>
        <a
                href="#" title="<?= $this->translate('Remove label') ?>"
                class="btn btn-default btn-trash align-middle job-label"
                data-id="__id__" data-text="__text__">
            <span class="btn-text">__text__</span>
            <span class="glyphicon glyphicon-trash small"></span>
            <input type="hidden" name="labels[]" value="__id__" />
        </a>
        <?php $labelTemplate = ob_get_clean(); ?>
        <div id="labels" data-template="<?= $this->escapeHtmlAttr($labelTemplate) ?>"></div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <label for="select-label">Label</label>
        <div class="input-group input-group-inline">
            <select name="select-labels" id="select-labels" class="form-control">
                <option value="CSE">Computer Science & Engineering</option>
                <option value="IAM">Industrial & Applied Mathematics</option>
                <option value="DS">Data Science</option>
            </select>
            <button type="button" id="btn-labels" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span><?= $this->translate('Add') ?>
            </button>
        </div>
    </div>
</div>
<script>
    var LabelList = function ($list, $dropdown, $submitBtn, $feedbackEmpty, labelSelector) {
        var _updateFeedback = function () {
            console.log($(labelSelector, $list).length);
            if ($(labelSelector, $list).length === 0) {
                $feedbackEmpty.show();

                return;
            }

            $feedbackEmpty.hide();
        };

        var _updateFormState = function () {
            // If there are no labels left to add
            if ($('option', $dropdown).length === 0) {
                $submitBtn.attr('disabled', 'disabled');
                return;
            }

            // Ensure that the submit button is enabled
            $($submitBtn).removeAttr('disabled');
        };

        var _updateState = function () {
            _updateFormState();
            _updateFeedback();
        }

        var _removeLabel = function ($label) {
            var option = $('<option />')
                .attr('value', $label.data('id'))
                .text($label.data('text'));

            // Remove label from list of added labels
            $label.remove();

            // Add option so that a user can re-add the label immediately
            $dropdown.append(option);

            _updateState();
        };

        var _addLabel = function ($option) {
            var template = $list.data('template');
            template = template.replace(/__id__/g, $option.val());
            template = template.replace(/__text__/g, $option.text());

            // Remove option to prevent user from adding duplicate labels
            $option.remove();

            $list.append(template);

            _updateState();
        };

        var _init = function () {
            $submitBtn.click(function (e) {
                _addLabel($('option:selected', $dropdown));

                return e.preventDefault();
            });

            $list.on('click', labelSelector, function (e) {
                _removeLabel($(this));

                return e.preventDefault();
            });

            _updateState();
        };

        _init();
    };

    var labelList = new LabelList(
        $('#labels'),
        $('#select-labels'),
        $('#btn-labels'),
        $('#labels-feedback--empty'),
        '.job-label'
    );
</script>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
<?= $this->form()->closeTag(); ?>
