<div class="row">
    <div class="col-md-12">
        <h3><?= $this->translate('Labels') ?></h3>
        <p class="text-muted"><?= $this->translate('No labels have been added yet') ?></p>

        <?php ob_start(); ?>
            <a
                href="#" title="<?= $this->translate('Remove label') ?>"
                class="btn btn-default btn-trash align-middle"
                data-id="__id__" data-text="__text__">
                <span class="btn-text">__text__</span>
                <span class="glyphicon glyphicon-trash small"></span>
                <input type="hidden" name="labels[]" value="__id__" />
            </a>
        <?php $labelTemplate = ob_get_clean(); ?>
        <div id="labels" data-template="<?= $this->escapeHtmlAttr($labelTemplate) ?>"></div>
    </div>
    <div class="col-md-6 form-group">
        <label for="select-label">Label</label>
        <div class="input-group input-group-inline">
            <select name="select-labels" id="select-labels" class="form-control">
                <option value="CSE">Computer Science & Engineering</option>
                <option value="IAM">Industrial & Applied Mathematics</option>
                <option value="DS">Data Science</option>
            </select>
            <button type="button" id="btn-labels" class="btn btn-default">
                <span class="glyphicon glyphicon-plus"></span><?= $this->translate('Add') ?>
            </button>
        </div>
    </div>
</div>
<script>
    $('#btn-labels').click(function () {
        var $selectedOption = $('#select-labels option:selected');

        var template = $('#labels').data('template');
        template = template.replace(/__id__/g, $selectedOption.val());
        template = template.replace(/__text__/g, $selectedOption.text());

        // Remove option to prevent user from adding duplicate labels
        $selectedOption.remove();

        if ($('#select-labels option').length === 0) {
            $(this).attr('disabled', 'disabled');
        }

        // Add label to list of added labels
        $("#labels").append(template);
    });

    $('#labels').on('click', '.btn-trash', function (e) {
        var option = $('<option />')
            .attr('value', $(this).data('id'))
            .text($(this).data('text'));

        // Remove label from list of added labels
        $(this).remove();

        // Add option so that a user can re-add the label immediately
        $('#select-labels').append(option);

        if ($('#btn-labels').is('[disabled]')) {
            $('#btn-labels').removeAttr('disabled');
        }

        return e.preventDefault();
    });
</script>
<?php
$form->setAttribute('class', 'form-horizontal');
$form->prepare();
?>

<?= $this->form()->openTag($form) ?>
<div class="row">
<?php foreach($form->getLanguages() as $lang):
$langDesc = $languages[$lang]
?>
<div class="col-md-6">
<h1><?= $this->translate($langDesc);?></h1>
<?php
$fieldset = $form->get('jobs')->get($lang);
?>
<?php
$element = $fieldset->get('id');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('name');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('slugName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('website');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('category');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('description');
$element->setAttribute('style', 'width:100%; height:10em; resize:none');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formTextArea($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('active');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formCheckbox($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('contactName');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('phone');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('email');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formInput($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>
<?php
$element = $fieldset->get('attachment_file');
$element->setAttribute('class', 'form-control');
?>
<div class="form-group<?= count($element->getMessages()) > 0 ? ' has-error' : '' ?>">
    <label for="<?= $element->getName() ?>" class="control-label col-sm-2">
        <?= $element->getOption('label') ?>
    </label>
    <div class="col-sm-10">
        <?= $this->formElement($element) ?>
        <?= $this->formElementErrors($element) ?>
    </div>
</div>

<?php if (isset($job) && !is_null($job->getAttachment())): ?>
<div class="form-group">
    <label class="control-label col-sm-2">
        <?= $this->translate('Current attachment') ?>
    </label>
    <div class="col-sm-10">
        <a class="btn btn-default" href="<?= $this->fileUrl($job->getAttachment()); ?>" >
            <?= $this->translate('View attachment'); ?>
        </a>
    </div>
</div>

<?php endif;?>
</div>
<?php endforeach;?>
</div>

<?php
$submit = $form->get('submit');
$submit->setLabel($this->translate('Save'));
$submit->setAttribute('class', 'btn btn-primary pull-right');
?>
<div class="form-group">
    <?= $this->formButton($submit) ?>
</div>
<?= $this->form()->closeTag(); ?>
