<?php

$slogan = $company->getTranslationFromLocale($locale)->getSlogan();

?>
<div id="company-<?= $company->getId(); ?>">
    <div class="row">
        <div class="col-md-12">
            <h1><?= $company->getName() ?></h1>
            <?php if (!empty($slogan)): ?>
                <p class="lead"><em><?= $slogan ?></em></p>
            <?php endif; ?>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="grid grid-col-2">
                <?php foreach ($this->jobCategories() as $category): ?>
                    <?php $url = $this->url('company/companyItem/joblist', [
                        'slugCompanyName' => $company->getSlugName(),
                        'category'        => $category->getSlug()
                    ]); ?>
                    <a
                        href="<?= $url ?>" class="card card-link"
                        title="<?= sprintf($this->translate('View all %s'), strtolower($category->getPluralName())) ?>">
                        <div><?= $category->getPluralName()?></div>
                        <div class="card-footer">
                            <span class="label label-primary">0</span>
                        </div>
                    </a>
                <?php endforeach; ?>
            </div>
            <hr />
            <div class="text-justify markdown">
                <?= $this->markdown($company->getTranslationFromLocale($locale)->getDescription()) ?>
            </div>
        </div>
        <div class="col-md-4">
            <?= $this->partial('partial/company/company/contact.phtml', [
                'locale'  => $locale,
                'company' => $company,
                'contact' => $company->getContactName(),
                'phone'   => $company->getPhone(),
                'email'   => $company->getEmail(),
                'website' => $company->getTranslationFromLocale($locale)->getWebsite(),
                'address' => $company->getAddress(),
            ]) ?>
        </div>
    </div>
</div>
